# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание товара'),
        ),
    ]
